// Maturity model, core principles and scoring-rubric content.
// Moved out of src/main.js unchanged (content only; the pages in src/pages/ render it).

export const PHASES = [
  { num:1, stage:'discovery', title:'Asset & Data Discovery', desc:'Inventory hardware, software, cloud resources, and data stores - including shadow IT. You can\'t protect what you don\'t know exists, and this is where most real gaps first surface.',
    monitor:'Tracked via a living asset inventory, reviewed whenever new systems, cloud resources, or vendors are added - not just annually.',
    evolve:'Once assets are known, Phase 2 can map real exposure instead of guessing at it.',
    inputs:'Hardware, software, and cloud resource lists; data stores; shadow IT reports.',
    output:'A living asset inventory covering every system and data store.',
    doneWhen:'Every asset can be named to an owner - nothing is on the network by surprise.' },
  { num:2, stage:'discovery', title:'Attack Surface Mapping', desc:'Identify every external-facing entry point - websites, APIs, VPNs, remote access, third-party integrations - and understand how an attacker would actually get in.',
    monitor:'Re-checked whenever external-facing infrastructure changes - new domains, new APIs, new remote-access points.',
    evolve:'A mapped surface is what makes Phase 4\'s gap analysis meaningful rather than generic.',
    inputs:'External-facing infrastructure: websites, APIs, VPNs, remote access, third-party integrations.',
    output:'A complete external attack-surface map showing every entry point.',
    doneWhen:'You can name every way in from outside, not just the obvious ones.' },
  { num:3, stage:'discovery', title:'Governance & Ownership Baseline', desc:'Assign real accountability for security decisions before writing a single control. Without an owner, findings from every later phase just accumulate unactioned.',
    monitor:'Verified through named accountability - can you point to the specific person who owns a given control?',
    evolve:'Without an owner, nothing found in later phases gets actioned - this single phase unlocks every one after it.',
    inputs:'Org chart, existing decision-making authority, current (if any) security responsibilities.',
    output:'Named ownership assigned for every security decision and control.',
    doneWhen:'You can point to the specific person accountable for any given control.' },
  { num:4, stage:'discovery', title:'Gap Analysis & Prioritization', desc:'Compare current state against a recognized framework (NIST CSF, CIS Controls) and rank gaps by risk - this is the exact function this site\'s Assessment tab performs.',
    monitor:'This is literally what the Assessment tab re-measures every time you run it - your score IS this phase\'s monitoring signal.',
    evolve:'Turns raw findings into an ordered backlog, which is what Phase 5 actually executes against.',
    inputs:'Current-state controls measured against a recognized framework (NIST CSF, CIS Controls).',
    output:'A ranked backlog of gaps ordered by risk - this is what the Assessment tab generates.',
    doneWhen:'Every gap has a severity ranking and a place in the backlog, not just a list of problems.' },
  { num:5, stage:'transformation', title:'Control Implementation', desc:'Roll out the prioritized technical controls - MFA, EDR, network segmentation, email authentication, backup isolation - turning the roadmap into deployed defenses.',
    monitor:'Tracked as percentage of the Phase 4 backlog actually deployed, not just planned or ticketed.',
    evolve:'Each control closed here is a specific finding that disappears from your next Assessment run.',
    inputs:'The prioritized gap backlog from Phase 4.',
    output:'Deployed technical controls - MFA, EDR, segmentation, email auth, backup isolation.',
    doneWhen:'The gap that triggered a control\'s deployment no longer shows up on the next Assessment.' },
  { num:6, stage:'transformation', title:'Policy & Documentation', desc:'Formalize the program in writing: security policy, incident response plan, backup/DR plan, risk register. See the Runbooks tab for what each of these should actually contain.',
    monitor:'Reviewed on the cadence the policy itself states - typically annually, or after any material infrastructure change.',
    evolve:'Turns implemented controls into an auditable, teachable program instead of tribal knowledge that leaves when one person does.',
    inputs:'Controls implemented in Phase 5, plus any regulatory or compliance obligations.',
    output:'Written policy, incident response plan, backup/DR plan, and risk register (see Runbooks).',
    doneWhen:'The program is documented well enough that someone new could follow it without tribal knowledge.' },
  { num:7, stage:'transformation', title:'Response Readiness & Testing', desc:'Rehearse the plans, don\'t just file them - tabletop exercises, restore drills from backup, and walkthroughs of the ransomware/phishing/DDoS runbooks before a real incident forces it.',
    monitor:'Measured by whether tabletop exercises and restore drills actually happened, not whether a plan merely exists on paper.',
    evolve:'The last step before a program is operational rather than aspirational - directly supported by the Runbooks tab.',
    inputs:'The written plans and runbooks produced in Phase 6.',
    output:'Completed tabletop exercises, backup-restore drills, and rehearsed runbook walkthroughs.',
    doneWhen:'Every plan has actually been rehearsed, not just filed.' },
  { num:8, stage:'optimization', title:'Continuous Monitoring & Tuning', desc:'Operationalize logging and detection, and tune it against real telemetry - an alert nobody trusts because of noise is functionally the same as no alert.',
    monitor:'Tracked via alert precision over time - false-positive rate trending down, not just alert volume trending up.',
    evolve:'Reliable detection is the precondition for Phase 9\'s audits meaning anything at all.',
    inputs:'Live telemetry - logs, alerts, and detection signals.',
    output:'Tuned detection with a signal-to-noise ratio the team actually trusts.',
    doneWhen:'False-positive rate is trending down, not just alert volume trending up.' },
  { num:9, stage:'optimization', title:'Auditing & Validation', desc:'Vulnerability scans, penetration tests, and control audits confirm defenses work as intended rather than just existing on paper - this is also where compliance audits (ISO 27001, SOC 2) fit in.',
    monitor:'Tracked via time-to-remediate findings from scans, pen tests, and compliance audits - not merely whether audits happened.',
    evolve:'Confirms which Phase 5 controls are actually working versus just installed and forgotten.',
    inputs:'Deployed controls and monitoring output from Phases 5 and 8.',
    output:'Vulnerability scan results, penetration test findings, and compliance audits (ISO 27001, SOC 2).',
    doneWhen:'Findings are tracked to remediation, not just discovered.' },
  { num:10, stage:'optimization', title:'Adaptive Iteration', desc:'Feed lessons from incidents, audits, and a changing threat landscape back into the program - and back into Phase 4\'s gap analysis, since this loop never really ends.',
    monitor:'Tracked by whether lessons from real incidents and audits visibly change next quarter\'s priorities.',
    evolve:'Feeds directly back into Phase 4 - the phase that makes the other nine a cycle instead of a one-time checklist.',
    inputs:'Lessons from real incidents, audit findings, and a changing threat landscape.',
    output:'Updated priorities fed back into Phase 4\'s gap analysis.',
    doneWhen:'Next quarter\'s priorities visibly reflect what was actually learned.' },
];

export const STAGE_DETAIL = {
  discovery: {
    summary:'The data-collection phase - your adaptive questionnaire across all six NIST CSF functions (Govern, Identify, Protect, Detect, Respond, Recover), shaped by your industry, region, and infrastructure so you only answer what actually applies.',
    metrics:'Every answer scores 0, 1, or 2 depending on the option chosen. A function\'s score is the sum of its answers divided by the maximum possible, as a percentage.',
  },
  transformation: {
    summary:'Where raw answers become an actual risk read, not just a total - every answer is cross-checked against every other answer for known dangerous combinations, then ranked into a priority action list.',
    metrics:'Compounding-risk flags are computed separately from the percentage score - two individually moderate gaps that combine into something materially worse each get surfaced as their own finding.',
  },
  optimization: {
    summary:'Re-running the assessment on a cadence to measure real change - which findings were resolved, which are newly flagged, and how the overall score has moved since the last run.',
    metrics:'History tracks a score delta between assessments, plus a resolved-vs-new breakdown per finding, so improvement is measured against your own baseline, not an abstract target.',
  },
};

// --- What each reading means (methodology 2.0, src/engine/scoring.js
// computeVerdict). Readings are decided in this order, so a percentage can
// never outvote a critical gap or an unverified critical control. ---
export const SCORE_RUBRIC = [
  { range:'Any coverage', verdict:'Critical gaps found', good:'Often plenty - many organizations here have most controls in place. The reading is about what is missing, not how much is present.',
    bad:'At least one critical control is not in place: MFA (or MFA for admins only while internet-reachable), internet-exposed remote admin, no endpoint protection, ad hoc patching with internet exposure, shared privileged accounts, backups that are not isolated or never restore-tested, or a flat or unsecured OT network.',
    why:'Each of these can decide on its own whether an attack succeeds or whether you can recover - the CISA Performance Goals and #StopRansomware guidance put them first for that reason.',
    priority:'Close the critical gaps first; they are all in the 30-day group of the action plan.' },
  { range:'Any coverage', verdict:'Verification needed', good:'No critical control is known to be missing.',
    bad:'At least one critical control was answered "Not sure".',
    why:'An unverified critical control is a real risk, just a smaller one than a confirmed gap - so it is ranked as something to confirm, not scored as a failure.',
    priority:'Find out - the action plan lists each one as "Find out: ...", with a 30-day target.' },
  { range:'Completeness under 60%', verdict:'Incomplete picture', good:'Whatever was answered is scored normally.',
    bad:'Fewer than 60% of applicable questions have a definite answer.',
    why:'"Not sure" and unanswered questions are excluded from coverage rather than counted as "No", so a high percentage built on a few answers would be misleading.',
    priority:'Fill in the unknowns, then read the percentage.' },
  { range:'Coverage below 40%', verdict:'High exposure', good:'No single critical gap was found.',
    bad:'Most controls are missing or partial.',
    why:'Coverage weights critical controls 3x and high-impact controls 2x, so a low figure means important controls, not just paperwork, are absent.',
    priority:'Work down the action plan in order; it is ranked by risk, not by questionnaire order.' },
  { range:'Coverage 40-64%', verdict:'Elevated exposure', good:'Baseline controls exist without a critical gap.',
    bad:'Many controls are missing or partial - often detection, response testing and governance.',
    why:'Partial answers count half; missing ones count zero, weighted by importance.',
    priority:'The 60-day group of the action plan is usually where the biggest gains are.' },
  { range:'Coverage 65-84%', verdict:'Moderate exposure', good:'Most controls are in place and no critical control is missing.',
    bad:'Several important controls are still missing or partial.',
    why:'The remaining gaps are real but no longer the kind that most often decide an incident on their own.',
    priority:'Finish the high-impact items and start testing what is in place (restore drills, tabletop exercises).' },
  { range:'Coverage 85% or more', verdict:'Strong foundations', good:'Core controls are in place, no critical gap, and at least 60% of questions have definite answers.',
    bad:'Combined findings and the remaining standard items still matter, and self-reported answers can be optimistic.',
    why:'Earned by definite answers - not by leaving hard questions unanswered.',
    priority:'Verify that controls work as described, and re-assess after significant changes.' },
];

export const CORE_PRINCIPLES = [
  { title:'Proactive, not reactive', desc:'Waiting for an incident to find your gaps is the most expensive way to learn about them. Assessing, monitoring, and fixing ahead of time is consistently cheaper than recovering afterward - the entire reason this site exists is to move that discovery earlier.' },
  { title:'People, process, and technology - not technology alone', desc:'A well-configured firewall behind an untrained employee and no documented process is still a weak posture. Real security improvement requires progress across all three, together, not a single expensive tool standing in for the other two.' },
  { title:'A culture, not a department', desc:"Security isn't something the IT team owns on everyone else's behalf. Every person who clicks a link, sets a password, or handles data is part of the control surface - the goal is a culture people grow into, not a policy document nobody reads." },
  { title:'Defense in depth', desc:'No single control is perfect, so no single control should be load-bearing. Layer defenses so that one failure - a missed patch, a clicked phishing link - doesn\'t cascade into a full compromise on its own.' },
  { title:'Assume adversaries have AI-augmented capabilities', desc:"Convincing phishing and voice/video impersonation are now cheap and fast to produce - an attacker doesn't need to have adopted AI themselves to benefit from tools that already do. This site treats AI-powered social engineering as a baseline assumption for every organization, not a special case reserved for those running AI systems - the same reasoning behind why its AI Readiness & Governance questions apply to everyone, not just organizations using AI." },
  { title:'Zero trust', desc:"Trust is not something a network location should grant automatically. Every request gets verified explicitly, regardless of whether it originates inside or outside the perimeter - the perimeter itself is no longer the control." },
  { title:'Least privilege', desc:'Access should match what a role genuinely needs to do its job, nothing more. Excess privilege sits quietly until the one day an account is compromised, at which point it becomes the attacker\'s privilege too.' },
  { title:'The CIA triad', desc:'Confidentiality, Integrity, and Availability - the three properties "secure" actually breaks down into. A control that protects one can quietly undermine another; good security design keeps all three in view at once, not just the one that feels most urgent.' },
  { title:'Segment the problem, not just the network', desc:"Looking at an entire security program at once is paralyzing. Breaking it into smaller, contained pieces - by function, by system, by risk - the same way network segmentation contains a breach, makes the work tractable and the containment real." },
  { title:'Decide from data, not instinct', desc:"Gut feeling about where the risk is usually points at the most visible problem, not the most likely one. Structured assessment, scoring, and trend tracking exist precisely to replace that instinct with evidence." },
  { title:'Improvement is a loop, not a destination', desc:"There's no final state where an organization is simply \"done\" being secure. Threats, infrastructure, and staff all change continuously, so the assessment is built to be re-run on a cadence, not completed once and filed away - the same loop this site's own animation is built around." },
];

// --- 10-phase maturity roadmap, organized into 3 clean, non-overlapping stages ---
export const RISK_SCORE_DESCRIPTIONS = {
  1: 'Minimal risk. Controls are comprehensive, tested, and continuously monitored across every function. This is an aspirational benchmark, not a typical starting point for most organizations.',
  2: 'Very low risk. A strong baseline across most functions, with only minor, well-understood gaps that are already being tracked.',
  3: 'Low risk. Core protections are in place and working; a few specific areas need attention, but nothing systemic.',
  4: 'Low-to-moderate risk. Foundational controls exist, but consistency and testing vary across the organization - some areas are solid, others untested.',
  5: 'Moderate risk. A genuine mix of solid and weak areas - the kind of profile where a single overlooked gap is enough to be exploited.',
  6: 'Moderate-to-elevated risk. Multiple functions show real gaps at once; an opportunistic attacker would likely find a way in without much effort.',
  7: 'Elevated risk. Significant gaps across several NIST functions, especially around detection and response - incidents would likely go unnoticed for a while.',
  8: 'High risk. Fundamental controls are missing or inconsistently applied. A breach isn\'t really a question of if, but when.',
  9: 'Very high risk. Minimal effective defenses in place - the organization would likely not detect an active compromise on its own.',
  10: 'Severe risk. Essentially an unmanaged security posture. Every function needs immediate, foundational work, starting with visibility into what even exists.',
};
