create table if not exists public.keepalive (
  id bigint generated by default as identity primary key,
  pinged_at timestamptz not null default now()
);

alter table public.keepalive enable row level security;

-- Anonymous read-only access, purely so the free-tier keep-alive ping
-- (using the anon key) can query a real table instead of hitting the
-- schema-introspection root, which requires service_role.
create policy "Allow anon read for keepalive ping"
  on public.keepalive
  for select
  to anon
  using (true);

insert into public.keepalive (pinged_at) values (now());
