create table public.news_items (
  id bigint generated by default as identity primary key,
  external_id text not null unique,
  headline text not null,
  body text not null,
  source text not null,
  source_url text,
  category text not null check (category in ('vuln', 'ot', 'ai', 'landscape')),
  published_at timestamptz not null,
  priority_score numeric not null default 0,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index news_items_priority_idx on public.news_items (priority_score desc, published_at desc);
create index news_items_category_idx on public.news_items (category);

alter table public.news_items enable row level security;

-- Public, read-only: anyone with the publishable/anon key can SELECT.
-- No insert/update/delete policy exists for anon/authenticated, so writes
-- are only possible via the service role (used internally by the
-- fetch-news Edge Function), matching the brief's "fetch job writes
-- directly to Supabase, client reads live" architecture.
create policy "Public read access"
  on public.news_items
  for select
  to anon, authenticated
  using (true);
